### ISSUE TITLE
OpenCV Java library not available

### ISSUE THREAD

**Issue by kleysonr** [Luca96/dlib-for-android#5]
Hi,

I'm trying to come up with an Android project where I can use OpenCV in both Java and C++ on the same project.

I'm able to configure OpenCV Java using this tutorial https://github.com/kleysonr/opencv_android , where OpenCV C++ doesn't work.

And now - **thanks for your great work on this** - I can also have a project with OpenCV C++, but not working for Java.

Have you tried to have both Java and C++ working on the same project ? Do you have any idea about what can be done in your configuration to have OpenCV Java working as well ?

Best Regards.

**Comment by Luca96** [comment]
Hi @kleysonr, 
I found a solution to integrate the Opencv java stuff with android.
You can find a detailed explanation in my article [here](https://medium.com/@luca_anzalone/setting-up-dlib-and-opencv-for-android-3efdbfcf9e7f).

Initially I followed your instruction (because I forgot the steps). But the AndroidStudio compiler complains about the fact that wasn't able to find `R.styleable`.
After some search I found that is necessary to edit the Opencv build.gradle by setting the variable **res.srcDirs = ['res']**.
After this fix everything works fine. I hope you can fix it too.

Best Regards.

**Comment by kleysonr** [comment]
Hi @Luca96,

Actually I got it working at the same day late night :) I was planning update this issue with the steps this weekend.

My steps was the same that you did.

Regarding the issue below, the step 6 in my instructions is to avoid it.

> After some search I found that is necessary to edit the Opencv build.gradle by setting the variable res.srcDirs = ['res'].

Best Regards.
Kleyson Rios.
